import type { RenderContext } from "./types";

/**
 * Hardcoded render context for tests/fixtures/sample_invoice.xml.
 * Generated by running the Python parser + render._build_context.
 *
 * In Phase B this will be replaced by an in-browser parser + helpers.
 */
export const mockContext: RenderContext = {
  invoice: {
    invoice_number: "FV/04/2026/001",
    invoice_type: "VAT",
    invoice_date: "2026-04-21",
    sale_date: "2026-04-30",
    currency: "EUR",
    exchange_rate: "4.2346",
    total_amount: "1234.56",
    total_amount_fmt: "1 234,56",
    seller: {
      nip: "1111111111",
      name: "PRZYKŁADOWA FIRMA SP. Z O.O.",
      address: {
        country_code: "PL",
        line1: "ul. Testowa 42/1",
        line2: "00-001 Warszawa",
      },
      vat_prefix: "PL",
      no_identifier: false,
    },
    buyer: {
      nip: "",
      name: "Example Corp",
      address: {
        country_code: "US",
        line1: "123 Main Street, Suite 100",
        line2: "New York, NY 10001",
      },
      vat_prefix: "",
      no_identifier: true,
      jst: false,
      gv: false,
    },
    line_items: [
      {
        line_number: 1,
        name: "Usługi informatyczne / IT services",
        unit: "usługa/service",
        quantity: "1",
        unit_net_price: "1234.56",
        net_value: "1234.56",
        tax_rate: "np I",
        exchange_rate: "4.2346",
        unit_net_price_fmt: "1 234,56",
        net_value_fmt: "1 234,56",
        tax_rate_display: "np.I*",
      },
    ],
    tax_summary: [
      {
        rate_code: "P_13_8",
        net_amount: "1234.56",
        tax_amount: "0.00",
        gross_amount: "1234.56",
        net_amount_fmt: "1 234,56",
        tax_amount_fmt: "0,00",
        gross_amount_fmt: "1 234,56",
        label: "np z wyłączeniem art. 100 ust 1 pkt 4 ustawy\nNot subject to tax in Poland",
      },
    ],
    annotations: {
      reverse_charge: true,
      cash_method: false,
      split_payment: false,
      self_invoicing: false,
      simplified_triangular: false,
    },
    payment: {
      form_code: "6",
      paid: "",
      terms: {
        quantity: "14",
        unit: "dni / days",
        starting_event:
          "od daty wystawienia faktury / from the date of issue of the invoice",
      },
      bank_account: {
        iban: "PL00123456780000000000000001",
        swift: "EXMPPLPW",
        bank_name: "Example Bank SA",
        description: "Rachunek EUR / EUR account",
      },
    },
    ksef_number: "",
  },
  invoice_type_pl: "Faktura podstawowa",
  invoice_type_en: "Standard Invoice",
  seller_country_pl: "Polska",
  seller_country_en: "Poland",
  buyer_country_pl: "Stany Zjednoczone Ameryki",
  buyer_country_en: "United States",
  payment_form_pl: "Przelew",
  payment_form_en: "Bank transfer",
  payment_status_pl: "Brak zapłaty",
  payment_status_en: "Not yet paid",
  amount_words_pl: "tysiąc dwieście trzydzieści cztery euro 56/100",
  amount_words_en: "one thousand, two hundred and thirty-four euro and fifty-six cents",
  exchange_rate_formatted: "4,234600",
  exchange_rate_is_global: true,
  annotation_lines: ["Odwrotne obciążenie / Reverse charge"],
  footnotes: [
    "np. - Nie podlega opodatkowaniu w Polsce. / Not subject to taxation in Poland.",
  ],
  qr_url:
    "https://qr.ksef.mf.gov.pl/invoice/1111111111/21-04-2026/8RTpaooWKCUo70XGY24S1a04_xRRDQVQaFe2kBsuI9k",
  qr_image:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQ4AAAEOAQAAAABQysQIAAACl0lEQVR4nO2aQYobQQxFX00ZvKy5QY6ivkGOZHIzGXKROUBAvRwo87NQdXuRhQ2ZTLpgCoNxWwsJSV//q7qIB+f28sgCvkz+pQkKgBr05jTvTVXqzasye9aP5O5zEZmkGlaDjKJKNaCpSorpInoBSlng2ps69CbWQhPrwlpOn+3Lx5k0Z11uZTmtS8dYi+T/y5e/MzmN7/Xy8xc1XrN5bt+c9ftn+/KxfSQHenNg+2lz9tGOdfbnB5gS67ZD847VMAUd25/PF1FYB0j09o51DOigsClzFNBcUm85hhyMpt4crM8YkdQzQYHCatABqJKkOmXVAaNxcshWedahsgiP5O6TOQJj1BgKRlxhNE0ZUSBJAZgkmgZuN83aR2G9eQ00KLdXeW8+umnKCWtsbIEmmhSWkC75lBGNSgNsNFGKo+bTIsMoszFPMQVVrhiUb8KIEtnY1WtCHM2ZtY/GMAWrSjGerHsD8CO5+/SE3YiclEWYBC+1+YQR2QbdIy+9qWYHwZwsKMn2nTBkT4FNiwwuecYiefaUhrJgTvQWiWncmU8dZE9T6iMpqV1OpbGKxGpW45TIQN2LTepJFbaRNOHm5CUx4b0st7KcuCaSn9ZC+0Euvw7m7sMjucJybZIJUpBKtqdaP5K7z3OGlA+DMzTtf00bke8iguabemVW7r3J8AwKLNWEwvJ6YsaIyG3JnXVrX+NPyb3vJEEKq/LtiSls4hzFWNnVMLZJlHdkE0a03fEN3UqK9L6L9CO5+/TmZKRD+53LtguaEL3vJh1KWXrz+nbpcJZ689O6HNTdhyZNpZQqZ70A57flvRTWy/vrMd19YCI5XPNeb7vFtLP8HNdzHM/dR2fHOponLAB9oxAT9lH5eovm8Ca/AYAWpwxZaZiFAAAAAElFTkSuQmCC",
};
